### ISSUE TITLE
facebook & google login

### ISSUE THREAD

**Issue by leonardosetiadi** [xtools-at/iOS-PWA-Wrapper#10]
my facebook & google login is not working, can you help?

**Comment by xtools-at** [comment]
can you be a little more specific? what's happening?

**Comment by leonardosetiadi** [comment]
In my web im using google and facebook for login, but when i try to login,
im not getting any callback from them

**Comment by xtools-at** [comment]
does the oauth login page open in the browser, or within the app?
can you provide a link to your web app?

**Comment by leonardosetiadi** [comment]
here is my website url www.kuismilioner.com

facebook login: go to browser, enter credentials, logged in in the browser
but not coming back to the apps
google login: go to browser, showing white blank page

**Comment by leonardosetiadi** [comment]
here is my website url www.kuismilioner.com

**Comment by xtools-at** [comment]
it makes sense if you think about it - you leave the app's browser context, the link opens in safari and everything else is only happening there, including the callback.
you could try extending/removing the _allowedOrigin_ logic after this line in `ViewController` and see if it works out for you:
`// restrict navigation to target host, open external links in 3rd party apps`

EDIT: pushed an update to `develop` to support multiple origins, maybe try adding facebook- and google-urls to the `Constants.swift` > _allowedOrigins_ array

**Comment by xtools-at** [comment]
any feedback on this?

**Comment by xtools-at** [comment]
@leonardosetiadi any feedback on this?

**Comment by xtools-at** [comment]
Closed due to lack of feedback from OP

**Comment by anirudhsirohi1729** [comment]
google login does'nt work even after extending and removing the func u mentioned
