### ISSUE TITLE
Question : how to "add your custom Javascript string to open your Web App's menu" ?

### ISSUE THREAD

**Issue by x4080** [xtools-at/iOS-PWA-Wrapper#11]
Hi, nice wrapper app, can you give an example how to :
```
add your custom Javascript string to open your Web App's menu.
this is injected into the site when the "Menu" button is pressed. This wrapper assumes you're hiding your Web App's header in favor of the native App navigation and show/hide your menu via Javascript.

```

Thanks

**Comment by xtools-at** [comment]
Look into the Constants.swift file, there's an example. It's just a piece of JS that is executed within your site on click (presuming the pwa header is hidden, the "real" menu icon would be invisible as well, see the sample app), put something in here which triggers your menu navigation

**Comment by x4080** [comment]
@xtools-at Thanks, and BTW I think now PWA is supported in ios 12 and up
