### ISSUE TITLE
When app launches access goes to browser

### ISSUE THREAD

**Issue by cakesoft-shivani** [xtools-at/iOS-PWA-Wrapper#16]
When app launches access goes to browser and my pwa app runs there in browser as simple website. 

Actually I want it to run it in our wrapped app. Why it redirecting me to browser if I wrap my website into app. 

Thanks.

**Comment by xtools-at** [comment]
Does it happen with the sample app too? Otherwise it may be some rouge code in your webapp causing this

**Comment by cakesoft-shivani** [comment]
Actually I take you code and done changes as per told thats it. It is happening on sample code.

**Comment by cakesoft-shivani** [comment]
Only changes are :
1) app icons
2) Launch icons
3) appTitle & webAppUrl variable in contants.swift file

**Comment by xtools-at** [comment]
your website may be causing this. does it happen too if you leave `webAppUrl` the same?

**Comment by cakesoft-shivani** [comment]
Its working for https://www.leasingrechnen.at this url, But my url worked for android app, then why its not working for ios?

**Comment by cakesoft-shivani** [comment]
@xtools-at, Could you please share manifest file for https://www.leasingrechnen.at/ this, So I can track whats wrong with my pwa manifest.

**Comment by xtools-at** [comment]
https://www.leasingrechnen.at/manifest.json

**Comment by xtools-at** [comment]
btw, did you update the "allowedOrigins" too to match your website's host?

**Comment by cakesoft-utkarsh** [comment]
@xtools-at This worked. correcting the "allowedOrigin" did the trick.
Thank you. This can be marked closed.
