### ISSUE TITLE
What about data storage with this wrapper ? 

### ISSUE THREAD

**Issue by Aarbel** [xtools-at/iOS-PWA-Wrapper#3]
1 - How much MB can we store in IndexDB and LocalStorage with this wrapper ?
2 - Can we access the Storage API ? for example to know the storage limit (cf [this conversation](https://stackoverflow.com/questions/35242869/what-is-the-storage-limit-for-a-service-worker))

Of course this question could be extended to your Android and Electron repos ;)

**Comment by xtools-at** [comment]
No clue, you need to try for yourself
