### ISSUE TITLE
This wrapper isn't working offline..

### ISSUE THREAD

**Issue by Aarbel** [xtools-at/iOS-PWA-Wrapper#4]
I tried with offline : 

1- Opened the app with my website PWA
2- Turn Airplane Mode ON
3- Kill PWA Wrapper APP
4- Reopened PWA Wrapper App
5- The PWA isn't loaded

Did i missed a step ?

**Comment by xtools-at** [comment]
Your PWA needs to use AppCache, ServiceWorker isn't supported in Safari yet

**Comment by simb4** [comment]
@xtools-at I'm using `applicationCache`, but it doesn't open it offline, may be I missed something?
1. cloned the repo
2. changed url, allowed host
3. Removed injected javascript
4. run online, everything works.
5. open app online (dowload into cache), then close
6. open app offline, offlineView appears, no cached data.

**Comment by simb4** [comment]
solved by extracting appcache part to iframe as it was done in example leasing app
