### ISSUE TITLE
How to remove the native App Title / Menu / Back button ? 

### ISSUE THREAD

**Issue by Aarbel** [xtools-at/iOS-PWA-Wrapper#5]
Those elements aren't necessary, because the navigation is everytime managed with html / css inside a PWA.

**Comment by xtools-at** [comment]
Just open the project in xcode and remove the titlebar altogether

**Comment by Aarbel** [comment]
Thanks

**Comment by FerX** [comment]
@Aarbel did you remove the menu?
@xtools-at I tried to delete it but then it doesn't compile.
is it not possible to have a fork without a menu?

thanks.
