### ISSUE TITLE
Disable bounce effect?

### ISSUE THREAD

**Issue by alexandernst** [xtools-at/iOS-PWA-Wrapper#6]
Is there a way to disable the bounce effect (overscroll) when scrolling down while at the top of the page? The page keeps scrolling down about 50-100px more and a white space shows up.

Visual examples:

![image](https://user-images.githubusercontent.com/89727/48986916-88b7f100-f11a-11e8-8b36-c17c3a36424a.png)

![image](https://user-images.githubusercontent.com/89727/48986926-99686700-f11a-11e8-8a6f-c38fac002f62.png)

**Comment by xtools-at** [comment]
I think that's default behaviour of Safari Webviews in iOS. You could look up the iOS docs for _WKWwebView_ and see if it can be disabled somehow.

**Comment by alexandernst** [comment]
Found it! It was easier than expected. Just add `webView.scrollView.bounces = false` in the `setupWebView`.

**Comment by xtools-at** [comment]
reopened issue, will try to find some time to enable this in the settings (or you could do a PR :) )
