### ISSUE TITLE
Disable zooming

### ISSUE THREAD

**Issue by alexandernst** [xtools-at/iOS-PWA-Wrapper#7]
IMHO you should allow disabling the zoom / pinch gestures.

    - class ViewController: UIViewController {
    + class ViewController: UIViewController, UIScrollViewDelegate {

Add to `setupWebView`

        // Disable zooming
        webView.scrollView.delegate = self
        webView.navigationDelegate = self

Add extra func:

    func scrollViewWillBeginZooming(_ scrollView: UIScrollView, with view: UIView?) {
        scrollView.pinchGestureRecognizer?.isEnabled = false
    }

**Comment by xtools-at** [comment]
Never ran into the issue, since my PWA's aren't zoomable by default already.

I don't have the time to prepare/test right now, but I'd be grateful if you could add this as a setting, trigger the functionality conditionally, test thoroughly and submit a PR ;)

**Comment by rewhex** [comment]
I think don't need to add this  in swift, cuz you can disable zoom via viewport meta tag with `user-scalable=no`.

**Comment by xtools-at** [comment]
Ok, so either use the appropriate meta tags in your html to prevent zooming, or someone puts together a tested PR like described by OP. closing here in the meantime.

**Comment by shekhardesigner** [comment]
FYA, `user-scalable=no` and similar values to disable zoom 'min,max-scale'  is ignored by default starting iOS 10. 

Ref - https://webkit.org/blog/7367/new-interaction-behaviors-in-ios-10/

**Comment by xtools-at** [comment]
[source](https://code.i-harness.com/en/q/185eb2f) for OP's proposal
added sample implementation on _develop_ branch, will merge into master if not causing issues
