### ISSUE TITLE
Remove menu

### ISSUE THREAD

**Issue by FerX** [xtools-at/iOS-PWA-Wrapper#9]
how can i remove the menu?
does anyone have a modified fork?

thanks.

**Comment by xtools-at** [comment]
you can try opening it in XCode, remove the app bar from the Storyboard, and all code referencing it (code issues should be underlined).
but you won't get your app approved by appstore without giving it some native touch, they don't like PWAs in general

**Comment by xtools-at** [comment]
closing here since there's no feedback for some time now, please reopen if you need further help
